---
- hosts: main
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python2
    disk_dir: /var/lib/libvirt/images
  vars_files:
    - /root/Migration-as-a-Service/{{ tenant_name }}/{{ tenant_name }}c1.yml

  tasks:
  - name: Create VM templates (C1)
    copy:
      src: /root/Migration-as-a-Service/ansible/templates/jinja/vm_main.xml.j2
      dest: /root/Migration-as-a-Service/{{ tenant_name }}/VM_templates/{{ item.1.name }}.xml.j2
    with_subelements:
      - "{{ Subnet }}"
      - vms
