---
- hosts: main
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python2

  tasks:

  - name: Define VMs
    virt:
      name: "VM11"
      command: define
      xml: "{{ lookup('template', 'VM11.xml.j2') }}"

  - name: Create VM
    virt:
      name: "VM11"
      command: create
      state: destroyed

  - name: Start VM
    virt:
      name: "VM11"
      command: start

- hosts: worker
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python2

  tasks:
  - name: Define VMs
    virt:
      name: "VM2"
      command: define
      xml: "{{ lookup('template', 'VM2.xml.j2') }}"

  - name: Create VM
    virt:
      name: "VM2"
      command: create
      state: destroyed

  - name: Start VM
    virt:
      name: "VM2"
      command: start
