---
- hosts: main
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - config_files/{{ tenant_name }}.yml
    - /root/Migration-as-a-Service/{{ tenant_name }}/{{ tenant_name }}c1.yml
  
  tasks:
  - name: Create Namespace
    vars: 
      ns_file: /var/run/netns/{{ item.ns_name }}
    command: ip netns add "{{ item.ns_name }}"
    args:
      creates: "{{ ns_file }}"
    with_items:
      - "{{ Subnet }}"

  - name: Create bridge inside namespace
    shell: |
      ip netns exec "{{ item.ns_name }}" brctl show | grep -w '^{{ item.bridge_name }}'; if [ $? -eq 1 ] ; then ip netns exec "{{ item.ns_name }}" brctl addbr "{{ item.bridge_name }}" ; fi
      ip netns exec "{{ item.ns_name }}" ip link set dev "{{ item.bridge_name }}" up
    with_items:
      - "{{ Subnet }}"

- hosts: worker
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - config_files/{{ tenant_name }}.yml
    - /root/Migration-as-a-Service/{{ tenant_name }}/{{ tenant_name }}c2.yml

  tasks:
  - name: Create Namespace
    vars:
      ns_file: /var/run/netns/{{ item.ns_name }}
    command: ip netns add "{{ item.ns_name }}"
    args:
      creates: "{{ ns_file }}"
    with_items:
      - "{{ Subnet }}"
  
  - name: Create bridge inside namespace
    shell: |
      ip netns exec "{{ item.ns_name }}" brctl show | grep -w '^{{ item.bridge_name }}'; if [ $? -eq 1 ] ; then ip netns exec "{{ item.ns_name }}" brctl addbr "{{ item.bridge_name }}" ; fi 
      ip netns exec "{{ item.ns_name }}" ip link set dev "{{ item.bridge_name }}" up
    with_items:
      - "{{ Subnet }}"
