---
- hosts: localhost
  gather_facts: False
  
  vars_files:
    - /root/Migration-as-a-Service/t1/t1c1.yml
  
  tasks:
  - name: Create bridge
    command: mkdir "{{ item.bridge_name }}"
    with_items:
      - "{{ Subnet }}"
