---
- hosts: main
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - config_files/{{ tenant_name }}.yml
    - /root/Migration-as-a-Service/{{ tenant_name }}/{{ tenant_name }}c1.yml
  
  tasks:
  - name: Create Tenant Namespace
    vars:
      ns_file: /var/run/netns/{{ item.name }}
    command: ip netns add "{{ item.name }}"
    args:
      creates: "{{ ns_file }}"
    with_items:
      - "{{ Namespace }}"

  - name: Create Subnet Namespace
    vars: 
      ns_file: /var/run/netns/{{ item.ns_name }}
    command: ip netns add "{{ item.ns_name }}"
    args:
      creates: "{{ ns_file }}"
    with_items:
      - "{{ Subnet }}"

  - name: Create Namespace VETH Pairs
    shell: |
      ip link show "{{ item.1.tenant_ns_if }}" ; if [ $? -ne 0 ] ; then ip link add "{{ item.1.tenant_ns_if }}" type veth peer name "{{ item.1.tenant_sub_if }}" ; fi
    with_subelements:
      - "{{ Subnet }}"
      - tenant_ns

  - name: Attach Namespace VETH Pairs
    shell: |
      ip netns exec "{{ item.1.tenant_ns_name }}" ip link show "{{ item.1.tenant_ns_if }}" ; if [ $? -ne 0 ] ; then ip link set "{{ item.1.tenant_ns_if }}" netns "{{ item.1.tenant_ns_name }}" ; fi
      ip netns exec "{{ item.0.ns_name }}" ip link show "{{ item.1.tenant_sub_if }}" ; if [ $? -ne 0 ] ; then ip link set "{{ item.1.tenant_sub_if }}" netns "{{ item.0.ns_name }}" ; fi
    with_subelements: 
      - "{{ Subnet }}"
      - tenant_ns

  - name: Set Namespace VETH Pairs UP
    shell: |
      ip netns exec "{{ item.1.tenant_ns_name }}" ip link set dev "{{ item.1.tenant_ns_if }}" up
      ip netns exec "{{ item.0.ns_name }}" ip link set dev "{{ item.1.tenant_sub_if }}" up
    with_subelements:
      - "{{ Subnet }}"
      - tenant_ns

  - name: Add IP addresses to Namespace VETH Pairs
    shell: |
      ip netns exec "{{ item.0.ns_name }}" ip addr show "{{ item.1.tenant_sub_if }}" | awk 'FNR==3{ print $2 }' | grep -w '^{{ item.1.tenant_sub_ip }}' ; if [ $? -ne 0 ] ; then ip netns exec "{{ item.0.ns_name }}" ip addr add "{{ item.1.tenant_sub_ip }}" dev "{{ item.1.tenant_sub_if }}" ; fi

      ip netns exec "{{ item.1.tenant_ns_name }}" ip addr show "{{ item.1.tenant_ns_if }}" | awk 'FNR==3{ print $2 }' | grep -w '^{{ item.1.tenant_ns_ip }}' ; if [ $? -ne 0 ] ; then ip netns exec "{{ item.1.tenant_ns_name }}" ip addr add "{{ item.1.tenant_ns_ip }}" dev "{{ item.1.tenant_ns_if }}" ; fi
    with_subelements:
      - "{{ Subnet }}"
      - tenant_ns

  - name: Create bridge inside namespace
    shell: |
      ip netns exec "{{ item.ns_name }}" brctl show | grep -w '^{{ item.bridge_name }}'; if [ $? -ne 0 ] ; then ip netns exec "{{ item.ns_name }}" brctl addbr "{{ item.bridge_name }}" ; fi
      ip netns exec "{{ item.ns_name }}" ip link set dev "{{ item.bridge_name }}" up
    with_items:
      - "{{ Subnet }}"

  - name: Create DNS VETH Pair
    shell: |
      ip netns exec "{{ item.0.ns_name }}" ip link show "{{ item.1.brif }}" ; if [ $? -ne 0 ] ; then ip netns exec "{{ item.0.ns_name }}" ip link add "{{ item.1.brif }}" type veth peer name "{{ item.1.dnsif }}" ; fi
      ip netns exec "{{ item.0.ns_name }}" ip link set dev "{{ item.1.brif }}" up
      ip netns exec "{{ item.0.ns_name }}" ip link set dev "{{ item.1.dnsif }}" up
    with_subelements:
      - "{{ Subnet }}"
      - dns

  - name: Attach DNS VETH Pair
    shell: |
      ip netns exec "{{ item.0.ns_name }}" brctl show "{{ item.0.bridge_name }}" | grep -w '{{ item.1.brif }}' ; if [ $? -ne 0 ] ; then ip netns exec "{{ item.0.ns_name }}" brctl addif "{{ item.0.bridge_name }}" "{{ item.1.brif }}" ; fi
    with_subelements:
      - "{{ Subnet }}"
      - dns
  
  - name: Create VETH Pairs
    shell: |
      ip link show "{{ item.1.brif }}" ; if [ $? -ne 0 ] ; then ip link add "{{ item.1.vmif }}" type veth peer name "{{ item.1.brif }}" ; fi
      ip link set dev "{{ item.1.brif }}" up
      ip link set dev "{{ item.1.vmif }}" up
    with_subelements:
      - "{{ Subnet }}"
      - vms
  
  - name: Attach VETH Pairs
    shell: |
      ip link show "{{ item.1.brif }}" ; if [ $? -eq 0 ] ; then ip link set "{{ item.1.brif }}" netns "{{ item.0.ns_name }}" ; fi
      ip netns exec "{{ item.0.ns_name }}" brctl show "{{ item.0.bridge_name }}" | grep -w '{{ item.1.brif }}' ; if [ $? -ne 0 ] ; then ip netns exec "{{ item.0.ns_name }}" brctl addif "{{ item.0.bridge_name }}" "{{ item.1.brif }}" ; fi
    with_subelements:
      - "{{ Subnet }}"
      - vms

  - name: All interfaces and bridges UP
    shell: |
      ip netns exec "{{ item.0.ns_name}}" ip link set "{{ item.1.brif }}" up
      ip netns exec "{{ item.0.ns_name }}" ip link set dev "{{ item.0.bridge_name }}" up
    with_subelements:
      - "{{ Subnet }}"
      - vms

  - name: Add IP to DNS Interface
    shell: |
      ip netns exec "{{ item.0.ns_name }}" ip addr show "{{ item.1.dnsif }}" | awk 'FNR==3{ print $2}'| grep -w '^{{ item.1.dnsif_ip }}' ; if [ $? -ne 0 ] ; then ip netns exec "{{ item.0.ns_name }}" ip addr add "{{ item.1.dnsif_ip }}" dev "{{ item.1.dnsif }}" ; fi
    with_subelements:
      - "{{ Subnet }}"
      - dns

  - name: Install DHCP Server
    shell: |
      ip netns exec "{{ item.0.ns_name }}" ps aux | grep -w '[d]nsmasq --interface {{ item.1.dnsif }}' ; if [ $? -ne 0 ] ; then ip netns exec "{{ item.0.ns_name }}" dnsmasq --interface "{{ item.1.dnsif }}" --dhcp-range={{ item.1.dhcp_start }},'{{ item.1.dhcp_end }}' ; fi
    with_subelements:
      - "{{ Subnet }}"
      - dns
