---
- hosts: localhost
  gather_facts: False
  
  vars_files:
    - config_files/{{ tenant_name }}.yml
    - /root/Migration-as-a-Service/{{ tenant_name }}/{{ tenant_name }}c1.yml
  
  tasks:
  - name: Create Namespace
    namespace:
      name: "{{ }}" 
      state: present
    with_items:
      - "{{ }}"
