---
- hosts: localhost
  gather_facts: False
  
  vars_files:
    - config_files/{{ tenant_name }}.yml
  
  tasks:
  - name: Create bridge
    nmcli:
      type: bridge
      conn_name: 'br'
      state: present
        
