---
- hosts: 
    - main
    - worker
  tasks:
  - name: Install libvirt packages if necessary
    apt:
      name:
      - qemu-kvm
      - libvirt-bin
      - python-libvirt
      - python-lxml
      - virt-manager
      - virt-viewer
      - virtinst
      - apache2
      - network-manager
      - libguestfs-tools
      state: present
    when: ansible_os_family == "Debian"
    become: yes
